### ISSUE TITLE
builder error: 'openssl/rand.h' not found

### ISSUE THREAD

**Issue by Victorem4Ever** [CesiumLabs/valkyria#1]
Hey, I tried to use your lib with a simple code but I had this error.
(I took the example code but obviously I edited it because it wasn't up to date ....)
I'm on windows.

**Comment by twlite** [comment]
Build it on WSL

**Comment by Victorem4Ever** [comment]
Thanks for the answer, I'll try or maybe just switch to linux because it's not the alone issue in windows.
